import {chromium} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync} from 'node:child_process';import {createHash} from 'node:crypto';
const out=path.resolve(process.env.ARTIFACTS_DIR||'artifacts/browser');await fs.mkdir(out,{recursive:true});const base=process.env.APP_URL||'http://127.0.0.1:4173';const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,chromiumSandbox:true});const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true,locale:'ja-JP',timezoneId:'UTC',reducedMotion:'reduce',serviceWorkers:'block'});const page=await context.newPage();const errors=[],checks=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('file:')&&!r.url().startsWith('blob:')&&!r.url().startsWith('data:'))external.push(r.url());});
// Keep interception subscribed across both real keyboard picker tests. A short-lived
// waitForEvent alone removes its listener after each chooser, asynchronously toggling
// Chromium interception off/on in Playwright 1.56.0. This observer never handles files.
let fileChooserEvents=0;page.on('filechooser',()=>{fileChooserEvents++;});
await page.addInitScript(()=>{window.__pickerEvents=[];for(const type of ['keydown','keyup','click'])document.addEventListener(type,event=>{if(!['open-file','file','open-receipt','receipt-file'].includes(event.target?.id)&&!event.target?.matches?.('.receipt-tools summary'))return;window.__pickerEvents.push({type,target:event.target.id||'receipt-summary',key:event.key||null,trusted:event.isTrusted,active:document.activeElement?.id||null,userActivation:navigator.userActivation?.isActive??null});if(window.__pickerEvents.length>40)window.__pickerEvents.shift();},true);});
const original=await fs.readFile('fixtures/orchard-bowl.cook','utf8');
async function check(name,fn){await fn();checks.push(name);console.log('PASS',name);}
async function analyzed(){await page.waitForFunction(()=>document.querySelector('#variant')?.disabled===false);}
async function ready(){await page.waitForFunction(()=>document.querySelector('#download-cook')?.disabled===false);}
async function reset(){await page.locator('#reset').click();await analyzed();}
async function selectRecipe(variant,grain){await page.locator('#variant').selectOption(variant);await page.locator('.alt-option').filter({hasText:'cooked '+grain}).locator('input').check();await page.locator('#review').click();await ready();}
async function download(button,filename,target){const wait=page.waitForEvent('download');await page.locator(button).click();const file=await wait;assert.equal(file.suggestedFilename(),filename);await file.saveAs(path.join(out,target||filename));assert.equal(await file.failure(),null);}
async function shot(name){await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});}
async function delayNextRead(){await page.evaluate(()=>{const old=File.prototype.arrayBuffer;File.prototype.arrayBuffer=function(...args){File.prototype.arrayBuffer=old;return old.apply(this,args).then(bytes=>new Promise(resolve=>{window.__releaseRead=()=>resolve(bytes);}));};});}
async function releaseRead(){await page.evaluate(()=>{window.__releaseRead();delete window.__releaseRead;});await page.waitForTimeout(50);}
try{
 await page.goto(base);await analyzed();
 await check('Japanese sample requires an explicit ingredient choice',async()=>{assert.equal(await page.locator('html').getAttribute('lang'),'ja');assert.equal(await page.locator('.alt-field').count(),1);assert.equal(await page.locator('input[type=radio]:checked').count(),0);assert.equal(await page.locator('#review').isDisabled(),true);assert.equal(await page.locator('#download-cook').isDisabled(),true);});
 await shot('desktop-ja-unselected');
 for(const variant of ['*','herb'])for(const grain of ['barley','rice']){const key=(variant==='*'?'default':variant)+'-'+grain;await check(`UI ${key} compiles and downloads actual selected.cook`,async()=>{await selectRecipe(variant,grain);assert.equal(await page.locator('#stat-steps').innerText(),variant==='herb'?'3':'2');await download('#download-cook','selected.cook',key+'.cook');await download('#download-receipt','choices.json',key+'.choices.json');});}
 await fs.copyFile(path.join(out,'herb-rice.cook'),path.join(out,'selected.cook'));await fs.copyFile(path.join(out,'herb-rice.choices.json'),path.join(out,'choices.json'));
 await shot('desktop-ja-reviewed');
 await check('actual UI exports match all three independent oracles',async()=>{for(const variant of ['*','herb'])for(const grain of ['barley','rice']){const key=(variant==='*'?'default':variant)+'-'+grain;execFileSync('python3',['scripts/oracle_validate.py','--file',path.join(out,key+'.cook'),'--variant',variant,'--grain',grain,'--report',path.join(out,key+'.oracle.json')],{stdio:'inherit'});}});
 await page.locator('#language').click();
 await check('English switch preserves choices and prepared result',async()=>{assert.equal(await page.locator('html').getAttribute('lang'),'en');assert.match(await page.locator('#review').innerText(),/Review selected recipe/);assert.equal(await page.locator('#variant').inputValue(),'herb');assert.equal(await page.locator('#stat-steps').innerText(),'3');assert.equal(await page.locator('#download-cook').isDisabled(),false);});
 await shot('desktop-en-reviewed');
 await check('keyboard tabs expose ingredient and branch differences',async()=>{await page.locator('#tab-recipe').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#tab-diff').getAttribute('aria-selected'),'true');assert.match(await page.locator('#view-diff').innerText(),/lemon juice/);assert.match(await page.locator('#view-diff').innerText(),/cooked barley/);await page.keyboard.press('End');assert.equal(await page.locator('#tab-cook').getAttribute('aria-selected'),'true');assert.equal(await page.locator('#output').textContent(),await fs.readFile(path.join(out,'selected.cook'),'utf8'));await page.keyboard.press('Home');});
 await page.locator('#tab-diff').click();await shot('desktop-en-diff');await page.locator('#tab-recipe').click();await page.pdf({path:path.join(out,'review-print.pdf'),format:'A4',printBackground:true,preferCSSPageSize:true});
 await check('ingredient edit immediately disables prior output',async()=>{await page.locator('.alt-option').filter({hasText:'cooked barley'}).locator('input').check();assert.equal(await page.locator('#download-cook').isDisabled(),true);assert.equal(await page.locator('#result').isVisible(),false);await page.locator('#review').click();await ready();});
 await check('variant change clears occurrence decisions',async()=>{await page.locator('#variant').selectOption('*');assert.equal(await page.locator('input[type=radio]:checked').count(),0);assert.equal(await page.locator('#review').isDisabled(),true);assert.equal(await page.locator('#download-cook').isDisabled(),true);});
 await selectRecipe('herb','rice');
 await check('source edit removes stale output and choices',async()=>{await page.locator('#source').fill(original+'\n');assert.equal(await page.locator('#download-cook').isDisabled(),true);assert.equal(await page.locator('#variant').isDisabled(),true);assert.equal(await page.locator('.alt-field').count(),0);});
 await check('stale receipt rejected after source reanalysis',async()=>{await page.locator('#analyze').click();await analyzed();await page.locator('#receipt-file').setInputFiles(path.join(out,'choices.json'));await page.waitForFunction(()=>document.querySelector('#status').classList.contains('error'));assert.match(await page.locator('#status').innerText(),/STALE/);assert.equal(await page.locator('#download-cook').isDisabled(),true);});await reset();
 await check('matching record restores the exact selected file',async()=>{await page.locator('#receipt-file').setInputFiles(path.join(out,'choices.json'));await ready();assert.equal(await page.locator('#variant').inputValue(),'herb');await download('#download-cook','selected.cook','replayed.cook');assert.equal(await fs.readFile(path.join(out,'replayed.cook'),'utf8'),await fs.readFile(path.join(out,'selected.cook'),'utf8'));});
 await check('malformed record invalidates prior output',async()=>{await page.locator('#receipt-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{')});await page.waitForFunction(()=>document.querySelector('#status').classList.contains('error'));assert.equal(await page.locator('#download-cook').isDisabled(),true);});await reset();
 await check('pending source file cannot overwrite a reset',async()=>{await delayNextRead();await page.locator('#file').setInputFiles({name:'late.cook',mimeType:'text/plain',buffer:Buffer.from('Late @oats{1%g}.')});await page.waitForFunction(()=>typeof window.__releaseRead==='function');await reset();await releaseRead();assert.equal(await page.locator('#source').inputValue(),original);assert.equal(await page.locator('#filename').innerText(),'orchard-bowl.cook');});
 await check('pending source file cannot overwrite newer typing',async()=>{await delayNextRead();await page.locator('#file').setInputFiles({name:'late.cook',mimeType:'text/plain',buffer:Buffer.from('Late @oats{1%g}.')});await page.waitForFunction(()=>typeof window.__releaseRead==='function');await page.locator('#source').fill('Newer @peas{1%g}.');await releaseRead();assert.equal(await page.locator('#source').inputValue(),'Newer @peas{1%g}.');assert.equal(await page.locator('#download-cook').isDisabled(),true);});await reset();
 await check('pending receipt cannot override a newer variant choice',async()=>{await selectRecipe('herb','rice');await delayNextRead();await page.locator('#receipt-file').setInputFiles(path.join(out,'choices.json'));await page.waitForFunction(()=>typeof window.__releaseRead==='function');await page.locator('#variant').selectOption('*');await releaseRead();assert.equal(await page.locator('#variant').inputValue(),'*');assert.equal(await page.locator('input[type=radio]:checked').count(),0);assert.equal(await page.locator('#download-cook').isDisabled(),true);});await reset();
 await check('pending review hash cannot revive output after an edit',async()=>{await page.locator('.alt-option').filter({hasText:'cooked rice'}).locator('input').check();await page.evaluate(()=>{const old=SubtleCrypto.prototype.digest;SubtleCrypto.prototype.digest=function(...args){SubtleCrypto.prototype.digest=old;return old.apply(this,args).then(hash=>new Promise(resolve=>{window.__releaseHash=()=>resolve(hash);}));};});await page.locator('#review').click();await page.waitForFunction(()=>typeof window.__releaseHash==='function');await page.locator('#source').fill(original+'\n');await page.evaluate(()=>{window.__releaseHash();delete window.__releaseHash;});await page.waitForTimeout(50);assert.equal(await page.locator('#source').inputValue(),original+'\n');assert.equal(await page.locator('#variant').isDisabled(),true);assert.equal(await page.locator('#download-cook').isDisabled(),true);assert.equal(await page.locator('#result').isVisible(),false);});await reset();
 for(let round=1;round<=2;round++){if(round>1)await reset();if(await page.locator('.receipt-tools').evaluate(e=>e.open)){await page.locator('.receipt-tools summary').focus();await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('.receipt-tools').open===false);}
 await check(`keyboard source picker has visible focus and imports fixture (round ${round})`,async()=>{await page.locator('#source').focus();await page.keyboard.press('Shift+Tab');await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'open-file');assert.equal(await page.locator('#open-file').evaluate(e=>e.matches(':focus-visible')),true);assert.notEqual(await page.locator('#open-file').evaluate(e=>getComputedStyle(e).outlineWidth),'0px');const wait=page.waitForEvent('filechooser');await page.keyboard.press('Enter');const chooser=await wait;assert.equal(await chooser.element().getAttribute('id'),'file');await chooser.setFiles('fixtures/orchard-bowl.cook');await analyzed();assert.equal(await page.locator('#source').inputValue(),original);});
 await check(`keyboard ingredient choice and review work (round ${round})`,async()=>{await page.locator('#variant').selectOption('herb');await page.locator('.alt-option').filter({hasText:'cooked rice'}).locator('input').focus();await page.keyboard.press('Space');await page.locator('#review').focus();await page.keyboard.press('Enter');await ready();});
 await check(`keyboard receipt picker restores matching record (round ${round})`,async()=>{await page.locator('.receipt-tools summary').focus();if(!await page.locator('.receipt-tools').evaluate(e=>e.open))await page.keyboard.press('Enter');await page.waitForFunction(()=>document.querySelector('.receipt-tools').open===true);await page.locator('#open-receipt').waitFor({state:'visible'});assert.equal(await page.locator('#open-receipt').isDisabled(),false);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.activeElement.id),'open-receipt');assert.equal(await page.locator('#open-receipt').evaluate(e=>e.matches(':focus-visible')),true);const wait=page.waitForEvent('filechooser');await page.keyboard.press('Enter');const chooser=await wait;assert.equal(await chooser.element().getAttribute('id'),'receipt-file');await chooser.setFiles(path.join(out,'choices.json'));await ready();assert.match(await page.locator('#receipt-status').innerText(),/matches/);assert.equal(await page.locator('#variant').inputValue(),'herb');assert.equal(await page.locator('#output').textContent(),await fs.readFile(path.join(out,'selected.cook'),'utf8'));});
 }
 for(const [name,source] of [['grouped','Mix @|a|a{1%g}|b{2%g}.'],['optional','Mix @?a{1%g}.'],['contradictory','== [herb] A ==\n\n[other] Add @x{1%g}.\n'],['malformed','Mix @a{1%g.'],['comment-prefix','[- a -] [herb] Add @mint{2%g}.\n\nStir.'],['metadata-boundary','>> title: Test\n[*] Mix @milk{1}|water{2}.\n\n[herb] Stir.']]){await check(`${name} syntax blocks output`,async()=>{await page.locator('#source').fill(source);await page.locator('#analyze').click();await page.waitForFunction(()=>document.querySelector('#status').classList.contains('error'));assert.equal(await page.locator('#download-cook').isDisabled(),true);});}
 await shot('desktop-en-blocked');await reset();
 for(const [name,buffer] of [['binary.cook',Buffer.from([0xff,0xfe,0x00])],['large.cook',Buffer.alloc(100001,97)]]){await check(`${name} import rejects and clears stale output`,async()=>{await selectRecipe('herb','rice');await page.locator('#file').setInputFiles({name,mimeType:'application/octet-stream',buffer});await page.waitForFunction(()=>document.querySelector('#status').classList.contains('error'));assert.equal(await page.locator('#download-cook').isDisabled(),true);await reset();});}
 await check('CRLF import preserves output bytes and source SHA256',async()=>{const crlf=original.replace(/\n/g,'\r\n');await page.locator('#file').setInputFiles({name:'windows.cook',mimeType:'text/plain',buffer:Buffer.from(crlf)});await analyzed();await selectRecipe('herb','rice');await download('#download-cook','selected.cook','crlf-selected.cook');await download('#download-receipt','choices.json','crlf-choices.json');const exported=await fs.readFile(path.join(out,'crlf-selected.cook'),'utf8');assert.ok(exported.includes('\r\n'));assert.ok(!/(?<!\r)\n/.test(exported));assert.equal(JSON.parse(await fs.readFile(path.join(out,'crlf-choices.json'),'utf8')).sourceHash,createHash('sha256').update(crlf).digest('hex'));});await reset();
 await check('BOM-prefixed imported branch does not leak into default',async()=>{const source='\uFEFF[herb] Add @mint{2%g}.\n\n[*] Stir.\n';await page.locator('#file').setInputFiles({name:'bom-branches.cook',mimeType:'text/plain',buffer:Buffer.from(source)});await analyzed();assert.deepEqual(await page.locator('#variant option').evaluateAll(options=>options.map(o=>o.value)),['*','herb']);await page.locator('#review').click();await ready();assert.equal(await page.locator('#output').textContent(),'Stir.\n');});await reset();
 await check('actual receipt larger than source cap reimports successfully',async()=>{const source='Mix @milk{1}|water{2}.\n\n'.repeat(500);await page.locator('#file').setInputFiles({name:'many.cook',mimeType:'text/plain',buffer:Buffer.from(source)});await analyzed();await page.evaluate(()=>{for(const field of document.querySelectorAll('.alt-field')){const input=field.querySelector('input');input.checked=true;input.dispatchEvent(new Event('change',{bubbles:true}));}});await page.locator('#review').click();await ready();await download('#download-receipt','choices.json','large-valid-choices.json');assert.ok((await fs.readFile(path.join(out,'large-valid-choices.json'))).length>100000);await page.locator('#receipt-file').setInputFiles(path.join(out,'large-valid-choices.json'));await ready();assert.equal(await page.locator('#stat-steps').innerText(),'500');});await reset();
 await check('source markup stays text without executing',async()=>{await page.locator('#source').fill('Mix @peas{1%g}. <img src=x onerror="window.COOKBRANCH_XSS=1">');await page.locator('#analyze').click();await analyzed();await page.locator('#review').click();await ready();assert.equal(await page.evaluate(()=>window.COOKBRANCH_XSS),undefined);assert.equal(await page.locator('#view-recipe img').count(),0);});await reset();await selectRecipe('herb','rice');
 for(const width of [390,320])for(const language of ['en','ja']){if(await page.locator('html').getAttribute('lang')!==language)await page.locator('#language').click();await page.setViewportSize({width,height:844});await check(`${width}px ${language} layout has no horizontal overflow`,async()=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const bad=await page.evaluate(()=>[...document.querySelectorAll('button,select,summary')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&(r.right>innerWidth+.5||r.left<-.5);}).map(e=>e.id||e.textContent));assert.deepEqual(bad,[]);});await shot(`mobile-${width}-${language}`);}
 await page.goto('file://'+path.resolve('dist/cook-branch.html'));await analyzed();await page.route('**/*',r=>r.abort());await check('offline self-contained page exports identical bytes',async()=>{await selectRecipe('herb','rice');await download('#download-cook','selected.cook','offline-selected.cook');assert.equal(await fs.readFile(path.join(out,'offline-selected.cook'),'utf8'),await fs.readFile(path.join(out,'selected.cook'),'utf8'));});
 await check('no runtime errors or external requests',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(external,[]);assert.equal(fileChooserEvents,4,'Both real keyboard file choosers must be observed in each of two rounds');});
 const report={schema:'cookbranch.browser-evidence/v1',status:'pass',checks:checks.length,names:checks,browser:browser.version(),sandbox:true,actualDownloads:4,offlineDownload:true,externalRequests:external.length,runtimeErrors:errors.length,fileChooserEvents,visualReview:'Screenshots and print PDF captured; separate pixel review is required'};await fs.writeFile(path.join(out,'browser-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
}catch(error){await shot('failure').catch(()=>{});await fs.writeFile(path.join(out,'browser-failure.json'),JSON.stringify({status:'failed',error:error.message,checks,errors,fileChooserEvents,pickerState:await page.evaluate(()=>({active:document.activeElement?.id||null,detailsOpen:document.querySelector('.receipt-tools')?.open??null,status:document.querySelector('#status')?.textContent||'',events:window.__pickerEvents||[]})).catch(()=>({unavailable:true}))},null,2)+'\n');throw error;}finally{await browser.close();}
